/**
 * Generate Types command - generates TypeScript types from registry
 */

import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'
import { compile } from 'json-schema-to-typescript'
import chalk from 'chalk'
import ora from 'ora'
import type { Component, ComponentRegistry } from '@seed-ship/mcp-ui-spec'

interface GenerateTypesOptions {
  namespace?: string
  exportAll?: boolean
}

export async function generateTypesCommand(
  input: string,
  output: string | undefined,
  options: GenerateTypesOptions
) {
  const spinner = ora('Loading registry...').start()

  try {
    // Read registry file
    const registryPath = resolve(process.cwd(), input)
    const registryContent = readFileSync(registryPath, 'utf-8')
    const registry: ComponentRegistry = JSON.parse(registryContent)

    spinner.text = 'Generating TypeScript types...'

    // Generate types for each component
    const typeDefinitions: string[] = []

    // Add header comment
    typeDefinitions.push('/**')
    typeDefinitions.push(' * Auto-generated TypeScript types from component registry')
    typeDefinitions.push(' * Generated by @seed-ship/mcp-ui-cli')
    typeDefinitions.push(' */')
    typeDefinitions.push('')

    if (options.namespace) {
      typeDefinitions.push(`export namespace ${options.namespace} {`)
    }

    // Generate types for each component
    for (const component of registry.components as Component[]) {
      spinner.text = `Generating types for ${component.id}...`

      // Generate interface name from component ID
      const typeName = componentIdToTypeName(component.id)

      try {
        const ts = await compile(component.schema as any, typeName, {
          bannerComment: `/* ${component.name} - ${component.description || 'No description'} */`,
          style: {
            semi: false,
            singleQuote: true,
          },
        })

        // Add the generated type
        if (options.namespace) {
          // Indent for namespace
          const indented = ts
            .split('\n')
            .map((line) => (line ? `  ${line}` : line))
            .join('\n')
          typeDefinitions.push(indented)
        } else {
          typeDefinitions.push(ts)
        }

        typeDefinitions.push('')
      } catch (error) {
        spinner.warn(`Skipping ${component.id}: type generation failed`)
        if (error instanceof Error) {
          console.error(chalk.yellow(`  ${error.message}`))
        }
      }
    }

    if (options.namespace) {
      typeDefinitions.push('}')
    }

    const generatedCode = typeDefinitions.join('\n')

    spinner.succeed('Type generation complete')

    // Write to file or stdout
    if (output) {
      const outputPath = resolve(process.cwd(), output)
      writeFileSync(outputPath, generatedCode, 'utf-8')
      console.log(chalk.green(`✓ Types written to ${output}`))
    } else {
      console.log('\n' + generatedCode)
    }

    process.exit(0)
  } catch (error) {
    spinner.fail('Type generation failed')

    if (error instanceof Error) {
      if (error.message.includes('ENOENT')) {
        console.error(chalk.red(`\nFile not found: ${input}`))
      } else {
        console.error(chalk.red('\nUnexpected error:'))
        console.error(chalk.gray(error.message))
      }
    }

    process.exit(1)
  }
}

/**
 * Convert component ID to TypeScript type name
 * Examples:
 *   quickchart-bar -> QuickchartBar
 *   metric-card -> MetricCard
 *   data-table -> DataTable
 */
function componentIdToTypeName(id: string): string {
  return id
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
