/**
 * Generative MCP UI - Type Definitions
 * Phase 0-3 Implementation
 *
 * Defines the contract for LLM-generated UI components
 */

/**
 * Component types supported by the renderer
 */
export type ComponentType =
  | 'chart'
  | 'table'
  | 'metric'
  | 'text'
  | 'grid'
  | 'iframe'
  | 'image'
  | 'link'
  | 'action'

/**
 * Chart types (powered by Quickchart)
 */
export type ChartType = 'bar' | 'line' | 'pie' | 'doughnut' | 'radar' | 'scatter'

/**
 * Grid layout specification (12-column system)
 */
export interface GridPosition {
  /**
   * Column start (1-12)
   */
  colStart: number

  /**
   * Column span (1-12)
   */
  colSpan: number

  /**
   * Row start (1-based, auto-increment if not specified)
   */
  rowStart?: number

  /**
   * Row span (default: 1)
   */
  rowSpan?: number
}

/**
 * Component resource limits (SECURITY)
 */
export interface ResourceLimits {
  /**
   * Max data points per chart (default: 1000)
   */
  maxDataPoints: number

  /**
   * Max table rows (default: 100, pagination required)
   */
  maxTableRows: number

  /**
   * Max payload size in bytes (default: 50KB)
   */
  maxPayloadSize: number

  /**
   * Iframe render timeout in ms (default: 5000ms)
   */
  renderTimeout: number
}

/**
 * Chart component parameters
 */
export interface ChartComponentParams {
  type: ChartType
  title?: string
  data: {
    labels: string[]
    datasets: Array<{
      label: string
      data: number[]
      backgroundColor?: string | string[]
      borderColor?: string | string[]
      borderWidth?: number
    }>
  }
  options?: {
    responsive?: boolean
    maintainAspectRatio?: boolean
    tension?: number
    scales?: any
    plugins?: any
  }
}

/**
 * Table component parameters
 */
export interface TableComponentParams {
  title?: string
  columns: Array<{
    key: string
    label: string
    sortable?: boolean
    width?: string
  }>
  rows: Array<Record<string, any>>
  pagination?: {
    currentPage: number
    pageSize: number
    totalRows: number
  }
}

/**
 * Metric card component parameters
 */
export interface MetricComponentParams {
  title: string
  value: string | number
  unit?: string
  trend?: {
    value: number
    direction: 'up' | 'down' | 'neutral'
  }
  subtitle?: string
  icon?: string
}

/**
 * Text component parameters
 */
export interface TextComponentParams {
  content: string
  markdown?: boolean
  className?: string
}

/**
 * Action component parameters
 */
export interface ActionComponentParams {
  label: string
  type: 'button' | 'link'
  action: 'tool-call' | 'link' | 'submit'
  toolName?: string
  params?: Record<string, any>
  url?: string
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  icon?: string
  disabled?: boolean
}

/**
 * UI Component definition (generated by LLM)
 */
export interface UIComponent {
  /**
   * Unique component ID
   */
  id: string

  /**
   * Component type
   */
  type: ComponentType

  /**
   * Grid position
   */
  position: GridPosition

  /**
   * Component parameters (type-specific)
   */
  params: ChartComponentParams | TableComponentParams | MetricComponentParams | TextComponentParams | ActionComponentParams

  /**
   * Metadata for observability
   */
  metadata?: {
    generatedAt: string
    llmModel?: string
    confidence?: number
    toolsUsed?: string[]
  }
}

/**
 * UI Layout (collection of components)
 */
export interface UILayout {
  /**
   * Layout ID
   */
  id: string

  /**
   * Components in the layout
   */
  components: UIComponent[]

  /**
   * Grid configuration
   */
  grid: {
    columns: number // Always 12 for Bootstrap-like grid
    gap: string // CSS grid-gap value
    minRowHeight?: string
  }

  /**
   * Layout metadata
   */
  metadata?: {
    query: string
    generatedAt: string
    llmModel?: string
    totalComponents: number
  }
}

/**
 * Component registry entry
 */
export interface ComponentRegistryEntry {
  /**
   * Component type identifier
   */
  type: ComponentType

  /**
   * Component name
   */
  name: string

  /**
   * Component description (for LLM context)
   */
  description: string

  /**
   * JSON schema for validation
   */
  schema: any

  /**
   * Example usage (for LLM few-shot prompting)
   */
  examples: Array<{
    query: string
    component: UIComponent
  }>

  /**
   * Resource limits
   */
  limits: ResourceLimits
}

/**
 * Component validation result
 */
export interface ValidationResult {
  valid: boolean
  errors?: Array<{
    path: string
    message: string
    code: string
  }>
}

/**
 * Renderer error types
 */
export type RendererErrorType =
  | 'validation'
  | 'render'
  | 'timeout'
  | 'resource_limit'
  | 'network'
  | 'security'

/**
 * Renderer error
 */
export interface RendererError {
  type: RendererErrorType
  message: string
  componentId?: string
  details?: any
}

/**
 * Streaming event types (Phase 2)
 */
export type StreamEventType =
  | 'status'
  | 'component-start'
  | 'component'
  | 'component-complete'
  | 'error'
  | 'complete'

/**
 * Streaming event (Phase 2)
 */
export interface StreamEvent {
  event: StreamEventType
  data: any
  sequenceId?: number
  timestamp: string
}
